"""empty message

Revision ID: cb57b767a986
Revises: 
Create Date: 2019-11-28 10:31:58.327058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb57b767a986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('roles', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('view_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=False),
    sa.Column('linkdata', sa.String(length=2000), nullable=False),
    sa.Column('tbscore', sa.String(length=50), nullable=False),
    sa.Column('vaderscorePos', sa.String(length=50), nullable=False),
    sa.Column('vaderscoreNeut', sa.String(length=50), nullable=False),
    sa.Column('vaderscoreNeg', sa.String(length=50), nullable=False),
    sa.Column('vaderscoreComp', sa.String(length=20), nullable=False),
    sa.Column('prof', sa.String(length=50), nullable=False),
    sa.Column('pubDate', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_posts')
    op.drop_table('user')
    # ### end Alembic commands ###
